MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :sessions #, only:[:new, :create, :destroy]
  resources :users #, only:[:new, :create, :show]
  # root to: redirect('/users')
  #get 'session/new', to: 'sessions#new', as "session"
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  # validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, uniqueness: true 
  before_validation :ensure_session_token
  attr_accessor :password

  def self.from_seed(email, password)
    user = User.new(email: email, password_digest: '11111111', session_token: '8')
    user.password = password
    user.reset_session_token!
    user.save!
    user
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save! #?not sure why this is necessary
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
    @session_token = self.session_token
    #do we need a self.save here?
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
    #? why don't we use self.save here?
    #?because activerecord does it for us? (if so then see line 17)
  end

  def valid_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil
    return user if user.valid_password?(password)
    nil

  end

end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logout!

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token! if current_user
    session[:session_token] = nil
  end

  def current_user
    User.find_by(session_token: session[:session_token])
  end

end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create

    user = User.find_by(email: params[:user][:email])

    render plain: "user not found" if user.nil?
    debugger
    if user.valid_password?(params[:user][:password])
      @user = user
      login!(user)
      render :show
      debugger
    else
      #render json: user.errors.full_messages
      debugger
      redirect_to sessions_url
    end
  end

  def new
    render :new
  end

  def show
    render :show
  end

  def destroy
    debugger 
    logout!
    redirect_to users_url
  end

end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    user = User.new(user_params)
    debugger
    if user.save
      @user = user
      login!(user)
      render json: user
    else
      #render json: user.errors.full_messages
      redirect_to users_url
    end

  end


  def index
    render :index
  end

  def new
    debugger
    render :new
  end

  def show
    # debugger
    render :show
  end



  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music____App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if current_user %>
      <h2>welcome, <%= current_user.email%></h2>
      <form  action="<%=sessions_url%>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
        <input type="submit"  value="log out">
      </form>
    <%else %>
    <form  action="<%=new_sessions_url%>" method="get">
      <input type="submit"  value="log in">
    </form>
    <%end %>
    <%= yield %>
  </body>
</html>

MusicApp/app/views/users/index.html.erb
<h1>index:</h1>
<ul>
  <%User.all.each do |user|%>
    <li>
      "<%=user.email%>"
    </li>
  <%end%>
</ul>

MusicApp/app/views/users/new.html.erb
<h1>NEW USER</h1>

<form action="<%=users_url%>" method="post">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <br>
  <label for="user_email">email:</label>
  <input id = 'user_email' type="text" name="user[email]" >
  <br>
  <label for="user_password">password</label>
  <input id = 'user_password' type="password" name="user[password]" >
  <br>
  <input type="submit">

</form>

MusicApp/app/views/users/show.html.erb
<h1>showing:</h1>
<%if current_user %>
<p>
  "<%=current_user.email%>"
</p>
<%end%>